### ISSUE TITLE
README.md does not match reality

### ISSUE THREAD

**Issue by n00ris** [thmhoag/arkserver#21]
## Image Setup Details

* **1.4.3**: 

I'm not sure the  Readme.md is correct after
https://github.com/thmhoag/arkserver/pull/11

If I start the docker and I do not add am_arkflag_crossplay, then the entry is missing in the arkmanager.cfg.
If it is missing, afaik the default is false.
My preferred solution would be to explicitly set arkflag_crossplay=true per default.

**Comment by thmhoag** [comment]
Hey @n00ris, you are correct. For now, I'll update the README.md to reflect that the value is `false` by default. 

I'm not necessarily partial to having the default value be one or the other, but before I change it I'd like to verify that it won't have any impact on servers with mods first (since Crossplay servers can't currently use mods). 

According to the ARK server documentation it shouldn't, but we all know how those docs can be sometimes... 😄
